name: workflow_APPROVAL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build and test
        run: echo "build and test"

  approval:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: https://example.com   # اختياري
    steps:
      - name: Wait for manager approval
        run: echo "This job will pause until approval is given."
