name: cicd Pipeline
on:
  push

jobs:
  test1:
    runs-on: ubuntu-latest
    outputs:
      KEY: ${{ steps.first_step.outputs.KEY}}
    steps:
      - name: first step 
        id : first_step
        run: |
           echo "KEY=API" >> $GITHUB_ENV
           echo "KEY=API" >> $GITHUB_OUTPUT


      - name: second step
        run: |
            echo " the value is $KEY "
            echo " the value is ${{ env.KEY }} "
            echo " the value is ${{ steps.first_step.outputs.KEY }} "

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: step in test2
        run: |
           echo " this is test2 "
           echo " the value is ${{ needs.test1.outputs.KEY }}"
