name: CICD Pipeline for Frontend 
on:
  push

jobs:
  test:
    outputs:
      KEY: ${{ steps.test.outputs.KEY }}  
    runs-on: ubuntu-latest
    steps:
      - name: test-code
        id: test
        run: echo "KEY=apex" >> $GITHUB_ENV

      - name: show-env
        run: echo "the value is  ${{ env.KEY }} or can be written as ${{ steps.test.outputs.KEY }}" 

  test2:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: show-env-2
        run: echo "the value from previous job is  ${{ steps.test.outputs.KEY }} or can be written as ${{ env.KEY }}"
