name: manual_workflows
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "Deploying to ${{ inputs.environement }} environment"
