name: test-disbatch-non-default-branch


on:

  workflow_dispatch:

jobs:
  test:
    name: test-dispatch
    runs-on: ubuntu-latest
    steps:
      - name: hello-non-default
        shell: bash
        run: echo "hello"
