name: CI/CD Pipeline

on: workflow_call

jobs:
  detect-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Branch: ${{ github.ref }}"
          echo "Merged: ${{ github.event.pull_request.merged }}"
          echo " Environment: ${{ input.APP_ENV }} or $APP_ENV "
          echo " github_workflow: ${{ github.workflow }}
