name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  detect-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Branch: ${{ github.ref }}"
          echo "Merged: ${{ github.event.pull_request.merged }}"
