name: CI/CD Event Tester

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  event-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print event info
        run: |
          echo "============================"
          echo "🔹 EVENT NAME: ${{ github.event_name }}"
          echo "🔹 BRANCH: ${{ github.ref }}"
          echo "🔹 ACTOR: ${{ github.actor }}"
          echo "🔹 SHA: ${{ github.sha }}"
          echo "🔹 HEAD REF: ${{ github.head_ref }}"
          echo "🔹 BASE REF: ${{ github.base_ref }}"
          echo "============================"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run simple test
        run: echo "✅ Workflow triggered successfully!"
